require_relative 'photo_index/options'
require_relative 'photo_index/photo'
require_relative 'photo_index/index'
require_relative 'photo_index/show_possible_dups'
require_relative 'photo_index/photo/metadata'
